stages:
  - sonarqube
  - build

build_linux:
  stage: build
  image: electronuserland/builder
  artifacts:
    paths:
    - app-builds/*.deb
  script:
    - npm i
    - npm run electron:linux
    - npm run clean
  only:
    - tags
    # - npm run electron:mac

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "http://your-gocd-server:9000"
    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
    SONAR_ANALYSIS_MODE: "issues"
  script:
  - /usr/bin/sonar-scanner-run.sh
# build_windows:
#   stage: build
#   image: electronuserland/builder:wine
#   script:
#     - npm i
#     - npm run electron:windows
